### ISSUE TITLE
Wonder about tofGetModel

### ISSUE THREAD

**Issue by Nvnhan010599** [viktorvano/3D-Scanner#1]
Yeah, When I clone your code and run it, the result couldn't appear. And I check code, in *__tof.c__* file in line : 
> *#806  HAL_I2C_Master_Receive(&hi2c2, **ToF_Device_Address + 1**, &ucTemp, 1, 1000);* 
> *#817 HAL_I2C_Master_Receive(&hi2c2, **ToF_Device_Address + 1**, &ucTemp, 1, 1000);*

and I replaced it : 
> *#806  HAL_I2C_Master_Receive(&hi2c2, **ToF_Device_Address**, &ucTemp, 1, 1000);* 
> *#817 HAL_I2C_Master_Receive(&hi2c2, **ToF_Device_Address**, &ucTemp, 1, 1000);*

Yah, it's working. So Can you explain to me that is a mistake or have other problems I still unknown. 

Thank you for your repo I can save my time and still do my work. 👍

**Comment by viktorvano** [comment]
![yrV0l](https://user-images.githubusercontent.com/25414104/118683668-dc928500-b801-11eb-84fc-5e6c9605b977.png)
Well that +1 should be for I2C reading. If you want to read you need to add 1 to your device address. 
Mine code works as it is and I own several of those ToF modules in several project sharing the same library.
I have used the same Tof library in NeuroBot project as well.

**Comment by Nvnhan010599** [comment]
[viktorvano] Oh, I have just realized my hardware wasn't stable. 
And following ur reply, I have known that In HAL library (STM32F1 or higher)  Address of the Device **may be need to add 1 or no** when we want to read the register of slaves. The proof is in _stm32f1xx_hal_i2c.c_ and _stm32f1xx_hal_i2c.h_ we have : 
- In define of I2C_MasterRequestRead , we have line 6583 (_stm32f1xx_hal_i2c.c_) : 
> hi2c->Instance->DR = I2C_7BIT_ADD_READ(DevAddress);

- line 668 (_stm32f1xx_hal_i2c.h_)
>  #define I2C_7BIT_ADD_READ(__ADDRESS__)                     ((uint8_t)((__ADDRESS__) | I2C_OAR1_ADD0)) 

- line 9280 (_stm32f1xb.h_)
>  #define I2C_OAR1_ADD0                       I2C_OAR1_ADD0_Msk                  /*!< Bit 0 */ 

And that is all. 
Thank you.
